import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { connectToDatabase } from "../api-lib/middleware/database";

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
      </Head>

      <div className="flex min-h-screen justify-center items-center">
        <head>
          <title></title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </head>

        <div className="max-w-xs rounded overflow-hidden shadow-lg my-2">
          <img
            className="w-full"
            src="https://tailwindcss.com/img/card-top.jpg"
            alt="Sunset in the mountains"
          />
          <div className="px-6 py-4">
            <div className="font-bold text-xl mb-2">
              {data.product_name} by {data.owner}
            </div>
            <p className="text-grey-darker text-base">
              Our first test product!
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps(contex) {
  const { db } = await connectToDatabase();

  const data = await db.collection("product").findOne({});

  // console.log(data);

  return {
    props: {
      data: JSON.parse(JSON.stringify(data)),
    },
  };
}
